In [2]:
import os
import numpy as np
from scipy import stats

import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

init_notebook_mode(connected=True)

In [3]:
path = 'readings/'

# Read every file in directory
readings = []
for filename in os.listdir(path):
    with open(path + filename, "r") as c:
        data = np.loadtxt(c, delimiter='\t')
        print(filename, data.shape)
        readings.append(data)

outdoors_umbrellas_tatum_center.txt (31, 3)
se_lounge1.txt (31, 3)
outdoors_calibrated.txt (31, 3)
m3_third_floor.txt (32, 3)
se_lab.txt (31, 3)
cs_club.txt (31, 3)
quantum_windows.txt (31, 3)
dc_lib_lower.txt (31, 3)
stc_second_floor.txt (31, 3)
dc_lib_upper.txt (31, 3)
stc_starbucks.txt (32, 3)
mc_coffee_and_doughnuts.txt (31, 3)


In [11]:
def get_stats(vals):
    n = len(vals)
    #vals = np.asarray(file).reshape((n,-1)) 
    #print(vals)
    #print(vals.shape)
    
    # Get readings
    ana = vals[:,0]
    pwm = vals[:,1]
    ser = vals[:,2]
    
    # Get stats
    #for arr in ana: #do not need the loop at this point, but looks prettier
    print("minmax: %s" % str(stats.describe(ana).minmax))
    print("mean: %s" % str(stats.describe(ana).mean))
    print(ser[:5])

In [12]:
for x in range(len(readings)):
    get_stats(readings[x])
    x_time = [i * 10 for i in range(len(readings[0]))] # time in seconds

minmax: (-73.0, 2873.0)
mean: 660.2903225806451
[ -1. 410. 410. 410. 410.]
minmax: (185.0, 964.0)
mean: 803.1612903225806
[410. 410. 410. 410. 410.]
minmax: (-73.0, 3148.0)
mean: 432.7096774193548
[410. 410. 410. 410. 410.]
minmax: (-73.0, 2675.0)
mean: 911.28125
[ -1. 410. 410. 410. 410.]
minmax: (307.0, 796.0)
mean: 701.9677419354839
[410. 410. 410. 410. 886.]
minmax: (-486.0, 995.0)
mean: 800.1290322580645
[ -1. 430. 410. 410. 410.]
minmax: (-73.0, 2660.0)
mean: 874.516129032258
[ -1. 410. 410. 410. 410.]
minmax: (-73.0, 2644.0)
mean: 761.0322580645161
[ -1. 410. 410. 410. 410.]
minmax: (-486.0, 1056.0)
mean: 857.3870967741935
[ -1. 430. 410. 410. 410.]
minmax: (-73.0, 2782.0)
mean: 856.8064516129032
[ -1. 410. 410. 410. 410.]
minmax: (-73.0, 2690.0)
mean: 890.15625
[ -1. 410. 410. 410. 410.]
minmax: (-486.0, 1270.0)
mean: 968.6774193548387
[ -1. 430. 410. 410. 410.]


In [7]:
x_time = [i * 10 for i in range(len(readings[0]))] # time in seconds

In [8]:
iplot([{"x": x_time, "y": readings[0][:,2]}])